// Haiku Daily — pre-generated pool.
// Each haiku is three lines [line1, line2, line3] plus an optional season tag.
// To add more: just append objects to this array and push to GitHub. No API needed.

const HAIKUS = [
  { lines: ["An old silent pond", "a frog jumps into the pond—", "splash! silence again"], season: "spring" },
  { lines: ["First warm morning light", "spills across the kitchen floor", "the cat stretches wide"], season: "spring" },
  { lines: ["Cherry blossoms fall", "one by one onto the path", "no one sweeps them up"], season: "spring" },
  { lines: ["Rain on the window", "the whole street turns to silver", "I forget my name"], season: "spring" },
  { lines: ["Green shoots through dark soil", "pushing toward a sky they've", "never seen before"], season: "spring" },
  { lines: ["A single white moth", "circles the porch light all night", "patient as the moon"], season: "spring" },
  { lines: ["New leaves unfolding", "the slow applause of the wind", "through the waking trees"], season: "spring" },
  { lines: ["Puddles hold the clouds", "a child leaps into the sky", "and lands with a laugh"], season: "spring" },
  { lines: ["Morning fog lifting", "the mountain remembers how", "to be a mountain"], season: "spring" },
  { lines: ["Bees in the clover", "the meadow hums a low note", "older than music"], season: "spring" },

  { lines: ["Long summer evening", "the light refuses to leave", "we let it stay late"], season: "summer" },
  { lines: ["Cicadas roaring", "the heat presses down like hands", "even shadows sweat"], season: "summer" },
  { lines: ["Cold watermelon", "juice running down my wrist—", "I am eight again"], season: "summer" },
  { lines: ["The ocean at noon", "ten thousand mirrors breaking", "and healing at once"], season: "summer" },
  { lines: ["Fireflies blinking", "the field keeps a thousand small", "secrets in the dark"], season: "summer" },
  { lines: ["A thunderstorm comes", "the dust smells suddenly sweet", "we run for the porch"], season: "summer" },
  { lines: ["Bare feet on hot stone", "then the shock of the cold creek", "summer in one step"], season: "summer" },
  { lines: ["Lazy ceiling fan", "stirring the thick afternoon", "nothing wants to move"], season: "summer" },
  { lines: ["Sunflowers all turn", "to follow the same bright face", "across the long day"], season: "summer" },
  { lines: ["Midnight still too warm", "we lie on the cooling roof", "counting falling stars"], season: "summer" },

  { lines: ["First cold morning air", "my breath becomes a ghost that", "waves and disappears"], season: "autumn" },
  { lines: ["One red maple leaf", "lets go without a struggle", "and the wind takes it"], season: "autumn" },
  { lines: ["Geese cross the gray sky", "writing a sentence southward", "no one can translate"], season: "autumn" },
  { lines: ["The harvest moon hangs", "enormous and orange and low", "as if it might fall"], season: "autumn" },
  { lines: ["Crunch of dry leaves", "the whole forest is brittle", "with letting things go"], season: "autumn" },
  { lines: ["Steam from the teacup", "fog outside the window glass", "two clouds keeping warm"], season: "autumn" },
  { lines: ["Empty swallow nest", "under the eaves, still perfect—", "they will not come back"], season: "autumn" },
  { lines: ["Apples in the bowl", "the kitchen smells of patience", "and the turning year"], season: "autumn" },
  { lines: ["Bare branches at dusk", "scratching their thin signatures", "across the cold moon"], season: "autumn" },
  { lines: ["The scarecrow stands guard", "over a field of nothing", "doing it so well"], season: "autumn" },

  { lines: ["First snow of winter", "the world holds its breath, then sighs", "into perfect white"], season: "winter" },
  { lines: ["Icicles drip slow", "the roof counting out the thaw", "one bright bead each time"], season: "winter" },
  { lines: ["Footprints in fresh snow", "behind me a small story", "the next snow will hide"], season: "winter" },
  { lines: ["The frozen river", "still moving somewhere beneath", "its silver silence"], season: "winter" },
  { lines: ["Bare trees in the frost", "each one a brilliant diagram", "of how to wait well"], season: "winter" },
  { lines: ["Woodsmoke on the wind", "somewhere a fire is keeping", "somebody alive"], season: "winter" },
  { lines: ["Long night, short cold day", "the sun a pale coin spent", "before we can blink"], season: "winter" },
  { lines: ["One crow on white snow", "the only ink in the world", "writing its dark word"], season: "winter" },
  { lines: ["Hands around warm tea", "outside the storm does its work", "in here, only steam"], season: "winter" },
  { lines: ["Stars sharp as needles", "the cold makes the whole sky close", "and impossibly clear"], season: "winter" },

  { lines: ["The mountain does not", "hurry to become itself", "and neither should you"], season: "any" },
  { lines: ["A door left open", "the whole night comes in slowly", "and rearranges things"], season: "any" },
  { lines: ["I planned my whole life", "the river laughed and kept on", "going its own way"], season: "any" },
  { lines: ["Stillness in the room", "even the dust in the light", "is in no hurry"], season: "any" },
  { lines: ["The candle burns down", "giving away all its light", "asking nothing back"], season: "any" },
  { lines: ["Between two heartbeats", "there is a small quiet door", "no one ever opens"], season: "any" },
  { lines: ["Old wooden bridge", "everyone who crossed is gone", "the river remains"], season: "any" },
  { lines: ["My empty teacup", "holds the shape of the morning", "and a little sky"], season: "any" },
  { lines: ["Lost on the long road", "I stop to watch an ant work—", "now I am not lost"], season: "any" },
  { lines: ["The lake at first light", "so still it forgets itself", "and becomes the sky"], season: "any" },
  { lines: ["Wind through tall grasses", "the field bows in every way", "the way the wind asks"], season: "any" },
  { lines: ["A single bell rings", "the sound travels out and out", "and never comes back"], season: "any" },
  { lines: ["The spider rebuilds", "for the third time today", "without complaining"], season: "any" },
  { lines: ["Moonlight on water", "I reach to hold a handful", "and hold only cold"], season: "any" },
  { lines: ["Tea leaves at the bottom", "of the cup spelling nothing", "I read them anyway"], season: "any" },
  { lines: ["The path disappears", "into mist on the hillside", "I walk into it"], season: "any" },
  { lines: ["A stone in the stream", "wearing smooth over decades", "in no rush to round"], season: "any" },
  { lines: ["Empty morning sky", "a single hawk draws a slow", "circle around nothing"], season: "any" },
  { lines: ["The clock on the wall", "insists it is going somewhere", "the wall stays put"], season: "any" },
  { lines: ["A held note fading", "the silence after music", "is also the song"], season: "any" },
  { lines: ["Two pine trees leaning", "the way old friends lean, saying", "nothing, meaning all"], season: "any" },
  { lines: ["The well's dark water", "holds one star down in the deep", "long after dawn comes"], season: "any" },
  { lines: ["I sweep the doorway", "the wind brings back the same leaves", "we have an arrangement"], season: "any" },
  { lines: ["Lantern in the fog", "a small warm rumor of home", "somewhere up ahead"], season: "any" },
  { lines: ["The tide goes out far", "leaving the whole beach written", "in the script of waves"], season: "any" },
  { lines: ["A crack in the cup", "lets the light find its way in", "is that not the point"], season: "any" },
  { lines: ["Morning glory vine", "claiming the fence overnight", "no one gave it leave"], season: "any" },
  { lines: ["The kettle's low song", "rising slowly to a peak", "then the quiet pour"], season: "any" },
  { lines: ["Snow on the lantern", "the small flame inside still warm", "doing its small work"], season: "winter" },
  { lines: ["I came for the view", "and stayed for the way the wind", "kept changing its mind"], season: "any" },

  { lines: ["Plum tree in the rain", "blossoms heavy with the weight", "of being so soon"], season: "spring" },
  { lines: ["Tadpoles in the ditch", "the whole future of the pond", "wriggling in warm mud"], season: "spring" },
  { lines: ["A robin tugging", "the long argument of a worm", "out of the soft lawn"], season: "spring" },
  { lines: ["Dew on the spiderweb", "the whole night's patient labor", "lit up for a breath"], season: "spring" },
  { lines: ["The willow loosens", "its long green hair in the wind", "and combs the river"], season: "spring" },
  { lines: ["Crocus through the snow", "small purple stubbornness says", "winter, you are done"], season: "spring" },
  { lines: ["A whole field of green", "where last month there was only", "the memory of green"], season: "spring" },
  { lines: ["The thaw drips all night", "the house ticking like a clock", "wound by the warm rain"], season: "spring" },
  { lines: ["Nest in the gutter", "two birds rebuild our argument", "about the downspout"], season: "spring" },
  { lines: ["First bee of the year", "bumbling into the window", "then out, unbothered"], season: "spring" },

  { lines: ["Heat shimmer rising", "the far road turns into water", "that we never reach"], season: "summer" },
  { lines: ["Screen door bangs open", "summer rushes in barefoot", "tracking light everywhere"], season: "summer" },
  { lines: ["The garden hose drinks", "then chokes, then gushes silver", "over the laughing kids"], season: "summer" },
  { lines: ["Crickets tune the dusk", "a slow and steady stitching", "of the night to day"], season: "summer" },
  { lines: ["Salt on sunburned skin", "the ocean's long afternoon", "still rolling in me"], season: "summer" },
  { lines: ["A peach so ripe it", "surrenders at the first bite", "down to the dark stone"], season: "summer" },
  { lines: ["Storm clouds stack like cliffs", "the whole sky leaning forward", "to tell us something"], season: "summer" },
  { lines: ["Hammock between trees", "I do absolutely nothing", "and do it all day"], season: "summer" },
  { lines: ["Moths at the streetlamp", "worshipping the wrong bright moon", "all the warm night long"], season: "summer" },
  { lines: ["The lake holds the heat", "long after the sun lets go", "we swim in spent gold"], season: "summer" },

  { lines: ["Chestnuts on the path", "split open and gleaming new", "no one taught them how"], season: "autumn" },
  { lines: ["Fog in the valley", "the church steeple wades out first", "then the sleeping town"], season: "autumn" },
  { lines: ["Pumpkins on the porch", "grinning at the early dark", "they are not afraid"], season: "autumn" },
  { lines: ["A spider's last web", "strung with the season's first frost", "abandoned, perfect"], season: "autumn" },
  { lines: ["Wind strips the orchard", "the trees let go of the year", "without a quarrel"], season: "autumn" },
  { lines: ["The smell of woodsmoke", "and somewhere a door closing", "against the cold dark"], season: "autumn" },
  { lines: ["Last warm afternoon", "the cat and I both know it", "and refuse to move"], season: "autumn" },
  { lines: ["Acorns on the roof", "the squirrels conduct their loud", "argument at dawn"], season: "autumn" },
  { lines: ["The river runs slow", "carrying its cargo of leaves", "to wherever leaves go"], season: "autumn" },
  { lines: ["Sweater weather comes", "I pull on the old gray one", "and the year fits again"], season: "autumn" },

  { lines: ["Snow falls on the lake", "each flake a brief white sentence", "the dark water reads"], season: "winter" },
  { lines: ["The window grows ferns", "of frost overnight—a garden", "that the morning melts"], season: "winter" },
  { lines: ["Boots squeak on the snow", "the only sound for a mile", "is me being cold"], season: "winter" },
  { lines: ["A single red scarf", "the brightest thing in the world", "crossing the white field"], season: "winter" },
  { lines: ["The pond freezes black", "then white—children come and write", "their names with their blades"], season: "winter" },
  { lines: ["Snowed-in and content", "the kettle and I agree", "to stay where we are"], season: "winter" },
  { lines: ["Bare oak in the storm", "holding its hundred empty", "cups out for the snow"], season: "winter" },
  { lines: ["The plow has gone through", "leaving the street two long walls", "of yesterday's sky"], season: "winter" },
  { lines: ["Breath fogs the cold glass", "I draw a sun with my thumb", "where the real one was"], season: "winter" },
  { lines: ["Deep midwinter hush", "the whole world holding still to", "let the year turn over"], season: "winter" },

  { lines: ["A locked door opens", "for the key it always knew", "would come home at last"], season: "any" },
  { lines: ["The map is not it", "fold the paper, lift your eyes—", "the road is right there"], season: "any" },
  { lines: ["What the silence holds", "is not the absence of sound", "but the room for it"], season: "any" },
  { lines: ["The river never", "asks the sea for permission", "to arrive at last"], season: "any" },
  { lines: ["An empty bench waits", "facing the long evening", "for whoever comes"], season: "any" },
  { lines: ["The same moon follows", "every traveler home, claiming", "each of them its own"], season: "any" },
  { lines: ["Footsteps in the hall", "then nothing—the house resumes", "its long conversation"], season: "any" },
  { lines: ["Two cups on the shelf", "one chipped, one whole, both waiting", "to be just as warm"], season: "any" },
  { lines: ["The wind has no name", "yet every tree in the world", "answers when it calls"], season: "any" },
  { lines: ["A coin in the well", "the wish sinks slow through cold light", "to rest with the rest"], season: "any" },
  { lines: ["The old dog dreaming", "his paws running through a field", "we will never see"], season: "any" },
  { lines: ["Dust in the sunbeam", "a slow galaxy turning", "above the still floor"], season: "any" },
  { lines: ["The page turns itself", "in the draft from the window—", "the story goes on"], season: "any" },
  { lines: ["A single sail far", "out where the blue meets the blue", "going, going, gone"], season: "any" },
  { lines: ["What the mirror keeps", "it gives back without keeping", "any of it long"], season: "any" },
  { lines: ["The clock stopped at three", "and ever since, that small room", "has been so peaceful"], season: "any" },
  { lines: ["A stranger's window", "lit gold against the blue dusk—", "someone is home there"], season: "any" },
  { lines: ["The path up the hill", "forgets itself in the grass", "then remembers near the top"], season: "any" },
  { lines: ["Rain on a tin roof", "the whole night spelling something", "in a patient code"], season: "any" },
  { lines: ["A feather drifting", "takes the longest way down, in", "no hurry to land"], season: "any" },
  { lines: ["The cellar's cool dark", "holding last summer's daylight", "in jars on the shelf"], season: "any" },
  { lines: ["A bell in the fog", "ringing for no ship I see", "yet I feel guided"], season: "any" },
  { lines: ["The cat finds the one", "warm square of sun on the floor", "and claims it for law"], season: "any" },
  { lines: ["Old letters, the ink", "fading toward the white again", "as if to start over"], season: "any" },
  { lines: ["The kite pulls and pulls", "wanting the sky for itself—", "I hold the thin string"], season: "any" },
  { lines: ["A pebble I keep", "for no reason but the way", "it fit my whole hand"], season: "any" },
  { lines: ["The last lit window", "goes dark—now the street belongs", "wholly to the stars"], season: "any" },
  { lines: ["Wind chimes in the night", "speaking the small bright language", "of nobody's words"], season: "any" },
  { lines: ["A door in the wall", "you walk past it every day—", "today, you go in"], season: "any" },
  { lines: ["The candle gutters", "throwing the whole quiet room", "into gentle question"], season: "any" },
  { lines: ["A train far away", "its long note pulling the night", "toward some other place"], season: "any" },
  { lines: ["The well of the cup", "where the last of the warm tea", "holds a small brown sky"], season: "any" },
  { lines: ["Footbridge over reeds", "the water beneath me goes", "where I cannot follow"], season: "any" },
  { lines: ["A book left face-down", "keeping the reader's place warm", "for whenever they return"], season: "any" },
  { lines: ["The hinge sings one note", "each time the day comes and goes", "through the garden gate"], season: "any" },
  { lines: ["A held breath let go", "the way the tide finally turns—", "without anyone's leave"], season: "any" },
  { lines: ["The shadow of birds", "crossing the wall of the house", "then only the wall"], season: "any" },
  { lines: ["Snow melts from the eave", "one bright bead, then the next bead", "spending the long thaw"], season: "winter" },
  { lines: ["A lamp in the storm", "keeping one small honest circle", "of the world in sight"], season: "any" },
  { lines: ["The roots hold all winter", "what the branches have to learn", "again every spring"], season: "any" },
  { lines: ["A boat at its rope", "tugging gently all night long", "dreaming of the sea"], season: "any" },
  { lines: ["The quiet after", "snow, when even the silence", "seems to have lain down"], season: "winter" },
];

// Make the list available to the page.
if (typeof module !== "undefined" && module.exports) {
  module.exports = HAIKUS;
}
